version: "3.8"

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "4060:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - orbital-network

  nats:
    image: nats:2.8.4
    restart: unless-stopped
    ports:
      - "4222:4222"
    networks:
      - orbital-network

  # gateway:
  #   build:
  #     context: .
  #     dockerfile: services/gateway/Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "${KILOAXE_SERVICES_GATEWAY_PORT}:${KILOAXE_SERVICES_GATEWAY_PORT}"
  #   environment:
  #     - JWT_SECRET=your_jwt_secret_here
  #   depends_on:
  #     - mongo
  #   networks:
  #     - orbital-network

  # world:
  #   build:
  #     context: .
  #     dockerfile: services/world/Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "${KILOAXE_SERVICES_WORLD_PORT}:${KILOAXE_SERVICES_WORLD_PORT}"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/kiloaxe
  #   depends_on:
  #     - mongo
  #   networks:
  #     - orbital-network

  # phaser:
  #   build:
  #     context: .
  #     dockerfile: clients/phaser/Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "${KILOAXE_CLIENTS_PHASER_PORT}:${KILOAXE_CLIENTS_PHASER_PORT}"
  #   networks:
  #     - orbital-network

volumes:
  mongo-data:

networks:
  orbital-network:
    driver: bridge
