module.exports = {
  apps: [
    // World service
    {
      name: "world",
      cwd: "services/@orbital/world",
      script: "npm",
      args: "run start:prod",
      env: {
        PORT: "4053",
      },
      error_file: "services/@orbital/world/logs/world.log",
      out_file: "services/@orbital/world/logs/world.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "world-watch",
      cwd: "services/@orbital/world",
      script: "npx",
      args: "nest start --watch",
      env: {
        PORT: "4053",
      },
      error_file: "services/@orbital/world/logs/world.log",
      out_file: "services/@orbital/world/logs/world.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "world-debug",
      cwd: "services/@orbital/world",
      script: "npx",
      args: "nest start --debug --watch",
      env: {
        PORT: "4053",
      },
      error_file: "services/@orbital/world/logs/world.log",
      out_file: "services/@orbital/world/logs/world.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
      node_args: "--inspect=9229",
    },

    // Admin Gateway service
    {
      name: "admin-gateway",
      cwd: "services/@orbital/admin-gateway",
      script: "npm",
      args: "run start:prod",
      env: {
        PORT: "4054",
      },
      error_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      out_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "admin-gateway-watch",
      cwd: "services/@orbital/admin-gateway",
      script: "npx",
      args: "nest start --watch",
      env: {
        PORT: "4054",
      },
      error_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      out_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "admin-gateway-debug",
      cwd: "services/@orbital/admin-gateway",
      script: "npx",
      args: "nest start --debug --watch",
      env: {
        PORT: "4054",
      },
      error_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      out_file: "services/@orbital/admin-gateway/logs/admin-gateway.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
      node_args: "--inspect=9230",
    },

    // Phaser Maps client
    {
      name: "phaser-maps",
      cwd: "clients/@orbital/phaser-maps",
      script: "node",
      args: "server.js",
      env: {
        PORT: "3000",
      },
      error_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      out_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "phaser-maps-watch",
      cwd: "clients/@orbital/phaser-maps",
      script: "yarn",
      args: "run dotenv -e .env.local next dev",
      env: {
        PORT: "3000",
      },
      error_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      out_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "phaser-maps-debug",
      cwd: "clients/@orbital/phaser-maps",
      script: "yarn",
      args: "run dotenv -e .env.local next dev",
      env: {
        PORT: "3000",
      },
      error_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      out_file: "clients/@orbital/phaser-maps/logs/phaser-maps.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
      node_args: "--inspect=9231",
    },

    // Phaser Game client
    {
      name: "phaser-game",
      cwd: "clients/@orbital/phaser-game",
      script: "node",
      args: "server.js",
      env: {
        PORT: "3001",
      },
      error_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      out_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "phaser-game-watch",
      cwd: "clients/@orbital/phaser-game",
      script: "yarn",
      args: "run dotenv -e .env.local next dev",
      env: {
        PORT: "3001",
      },
      error_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      out_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
    },
    {
      name: "phaser-game-debug",
      cwd: "clients/@orbital/phaser-game",
      script: "yarn",
      args: "run dotenv -e .env.local next dev",
      env: {
        PORT: "3001",
      },
      error_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      out_file: "clients/@orbital/phaser-game/logs/phaser-game.log",
      merge_logs: true,
      max_size: "10M",
      max_files: 10,
      node_args: "--inspect=9232",
    },
  ],
};
